**Dictionary in Python**

**List in Python**

In [ ]:
nums=[7,8,6,6]
nums.index(7) # it *returns index of element
nums.append(5) # it add element in list
nums.insert(4,1) # insert(index,element)
nums.remove(6) # removes all instances of 6
print(nums)
nums.extend([2,3,9,6])
print(nums)
nums.sort()
print(nums)
nums.pop()
print(nums)


[7, 8, 6, 1, 5]
[7, 8, 6, 1, 5, 2, 3, 9, 6]
[1, 2, 3, 5, 6, 6, 7, 8, 9]
[1, 2, 3, 5, 6, 6, 7, 8]


**Tuple in Python**

In [ ]:
#tuple elements cant be changed
t=(1,2,3,4)
print(t)

(1, 2, 3, 4)


**String in Python**

In [ ]:
#String slicing in Python


**Dictionary in Python**

In [ ]:
d={"name":"rahul","roll":54,"section":"D"}
print(d)
d.keys()


{'name': 'rahul', 'roll': 54, 'section': 'D'}


dict_keys(['name', 'roll', 'section'])

In [ ]:
d.values()
print(d.get('name'),"sectioin is ",d.get('section'))

rahul sectioin is  D


In [ ]:
dict = {'a':1,'b':2,'c':3}

dict.keys() # returns list of keys of dictionary
dict.values() # returns list of values of dictionary
dict.get('a') # returns value for any corresponding key
dict.items() # returns [('a',1),('b',2),('c',3)]
dict.copy() # returns copy of the dictionary
# NOTE : items() Returns view object that will be updated with any future
# changes to dict
#dict.pop(KEY) # pops key-value pair with that key
dict.popitem() # removes most recent pair added
#dict.setDefault(KEY,DEFAULT_VALUE)
# returns value of key, if key exists, else default value returned
# If the key exist, this parameter(DEFAULT_VALUE) has no effect.
# If the key does not exist, DEFAULT_VALUE becomes the key's value. 2nd
# argument's default is None.
#dict.update({KEY:VALUE})
# inserts pair in dictionary if not present, if present, corresponding value is
# overriden (not key)
# defaultdict ensures that if any element is accessed that is not present in
# the dictionary
# it will be created and error will not be thrown (which happens in normal dictionary)
# Also, the new element created will be of argument type, for example in the below line
# an element of type 'list' will be made for a Key that does not exist
#myDictionary = defaultdict(list)

**Operators** in **Python**


In [ ]:
# Assignment Operators
p=1
x=1
x+=5
a,b=4,9
print(p,x,a,b)

In [ ]:
#unary operator
n=7
n=-n
a=1
a+=a
print(a,n)

2 -7


**Numbers System Conversion**

In [ ]:
b=bin(25) #decimal to binary 25 =11001
print(b)
print(0b11001)
print("25 converted into octal",oct(25))
def fun(n):
    b=bin(n)
    print(b)
fun(25)

0b11001
25
25 converted into octal 0o31
0b11001


**Bitwise** **Operators**

In [ ]:
# operators are ~ ,
# 2's complement = 1's complement + 1
# ~12
#bitwise AND - & calculated in binary formate
# 12 & 13
#bitwise OR - |
# 12|13
#bitwise XOR -  ^
12 ^1
#bitwise left shift


13

## ***Bulit-in Data sturctures are List, Tuple , Dict, Set***

In [ ]:
list2=[5,1,2,1,"hello"]
print(list2.index(5)) #it returns index
list2.insert(4,4)
print(list2)
list2.insert(5,(5,6))
print(list2)
list2.extend((5,6))
print(list2)

0
[5, 1, 2, 1, 4, 'hello']
[5, 1, 2, 1, 4, (5, 6), 'hello']
[5, 1, 2, 1, 4, (5, 6), 'hello', 5, 6]


In [ ]:
list1=[]
for i in range(6):
  list1.append(6-i)
print(list1)
list1.sort()
print(list1)

[6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6]


## *Fuctions in python*


In [ ]:
#fuctions in python
#actual arguments
def person(name,age=18):
  print(name,age)

person('reddy',21)

person(22,'raj')  #Positional arguments
person('rahul')  #Default argument.


reddy 21
22 raj
rahul 18


In [ ]:
# *b will take tuple
def sum(a,*b):
  print(a)
  print(b) # *b is tuple
  c=a
  for i in b:
    c=c+i
  print(c)
sum(4,5,1,2)

4
(5, 1, 2)
12


In [ ]:
#keyworded varaible length  of arguments
#  **data will take both keyword and value
def person(name,**data):
  print(name)
  # print(data)
  for i,j in data.items():
    print(i,j)
person("mohd",age=26,city="hyd",mob=9870001562)

mohd
age 26
city hyd
mob 9870001562


In [ ]:
#lambda
add=lambda a,b : a+b
sq=lambda a:a**2
print(add(4,5))
sq(5)


9


25

In [ ]:
from IPython.utils.path import glob
#global keyword
a=10 # global var
print(id(a))
b=20
c=30
print("c:",c)
def fun():
  global b #now b can be changed
  a=15 #local var
  b=1002
  x=globals()['a']
  y=globals()['c']
  globals()['c']=45 # it will not change y value only changes c value to 45
  print(id(x),x)
  print("a,b inside fun :",a,b)


fun()
print("a,b outside fun :",a,b)
print("c:",c)

134220310577680
c: 30
134220310577680 10
a,b inside fun : 15 1002
a,b outside fun : 10 1002
c: 45


In [ ]:
#passing a list in function

def count(lst):
  e=0
  o=0
  for i in lst:
    if(i%2==0):
      e+=1
    else:
      o+=1
    return e,o
lst=[1,5,4,1,6,78,4,2]
even, odd = count(lst)
print("Even : {} and Odd : {}".format(even,odd))

Even : 0 and Odd : 1


In [ ]:
# take 10 names from user and display whose name len is more than 5
print("Give 10 names ...")
name=[]
for i in range(1,11):
  user=input("enter user {} name : ".format(i))
  name.append(user)
def checkName(lst):
  res=[]
  for i in lst:
    if(len(i)>5):
      res.append(i)
  return res
print("given names : ",name)
print("name which have more than 5 letters : ",checkName(name))


Give 10 names ...
enter user 1 name : jkasfdh
enter user 2 name : asraf
enter user 3 name : aasara
enter user 4 name : as
enter user 5 name : fggh
enter user 6 name : fghf
enter user 7 name : gjh
enter user 8 name : jjjjjjjjj
enter user 9 name : jg
enter user 10 name : fdfg
given names :  ['jkasfdh', 'asraf', 'aasara', 'as', 'fggh', 'fghf', 'gjh', 'jjjjjjjjj', 'jg', 'fdfg']
name which have more than 5 letters :  ['jkasfdh', 'aasara', 'jjjjjjjjj']


In [ ]:
#fibonacci series 0  1 1 2 3 5  8 13 21 ...
l=[0,1]
n=int(input("enter limit for series : "))
for i in range(2,n+1):
  f0=0
  f1=1
  f2=f0+f1
  f0=f1
  f1=f2
  l.append(f2)
print(l)

enter limit for series : 4
[0, 1, 1, 1, 1, 1]


In [ ]:
t=int(input("total : "))
m=int(input("enter no of months :"))
it=t*0.05*m
print(it)

total : 60000
enter no of months :18
54000.0


Anonymous Functions | lambda

In [ ]:
# lambda
sq=lambda a :a*a
print(sq(5))
ad=lambda a,b :a+b
print(ad(4,5))

25
9


In [ ]:
##filter(function,list) : filter based on function(condition)
nums=[3,2,6,8,4,5,7,9]
evens=list(filter(lambda n:n%2==0,nums))
print(evens)
#map() : when want to change all values
doubles=list(map(lambda d:d*2,evens))
print(doubles)
#reduce() : always take two values at a time
from functools import reduce
sum=reduce(lambda a,b:a+b,doubles)
print(sum)

[2, 6, 8, 4]
[4, 12, 16, 8]
40


In [46]:
# Reverse every word in a string
s=input("Enter a string : ")
l=s.split()
ans=""
for i in l:
  ans=ans+i[::-1]+" "
print(ans)


Enter a string : hello im
olleh mi 


# ***Arrays and numpy***


In [ ]:
# search key element in array
from array import *
arr=array('i',[]) # int array declaration
#taking user input
l=int(input("Enter the length of the array :"))
for i in range(l):
  u=int(input(f"{i+1} element : "))
  arr.append(u)
print(arr)
k=int(input("Enter element fro search : " ))
for i in range(len(arr)):
  if(arr[i]==k):
    print(f"{k} found at {i+1} position")
    break
else:
  print(f"{k} is not present in {arr}")

Enter the length of the array :3
1 element : 45
2 element : 67
3 element : 86
array('i', [45, 67, 86])
Enter element fro search : 67
67 found at 2 position


**numpy(1D,2D,.... Arrays )**

In [ ]:
# different ways to create a array
# 1. array()
from numpy import *
arr1=array([1,2,3,4,5.1]) # all values will be converted to float
# print(arr1.dtype)
#print(arr1)
#2. linspace()
arr2=linspace(0,10,20) # it create 20 parts
# print(arr2)
#3. arange()
arr3=arange(1,15,2) # arange(start,stop,step)
# print(arr3)
#4 logspace
arr4=logspace(1,40,5) # its based on log
# print('%2f' %arr4[0])
#5 zeros()
# print(zeros(5))
#6 ones()
# print(ones(6))
# operations
arr=array([1,2,3,4])
#print(arr)
arr=arr+5
print(arr)
# print(sin(arr))
# print(sqrt(arr))
# print(sum(arr))
# print(min(arr))
# print(sort(arr))
# print(unique(arr))
# coping a array in numpy and its should have same id(address)
#newArr=arr.view()  # change or updating values will be reflected to both arr and newArr (shalow copying )
newArr=arr.copy() #deep copying
#print(newArr)


[6 7 8 9]


**2D and multi D Arrays**

In [ ]:
ar1=array([
    [4,8,7,1,2,3],
    [5,9,3,4,5,6]
])
print(ar1)
print(ar1.dtype)
print(ar1.ndim)
print(ar1.shape)
print(ar1.size)
ar2=ar1.flatten()
print(ar2)
ar3=ar1.reshape(2,2,3) #3*4 or 2*2*3
print(ar3)

[[4 8 7 1 2 3]
 [5 9 3 4 5 6]]
int64
2
(2, 6)
12
[4 8 7 1 2 3 5 9 3 4 5 6]
[[[4 8 7]
  [1 2 3]]

 [[5 9 3]
  [4 5 6]]]


In [ ]:
### matrix
m=matrix('1 2 3 ; 6 4 5 ; 1 6 7') # space btw element and comma btw each list
print(m)
print(m.max())
print(diagonal(m))


[[1 2 3]
 [6 4 5]
 [1 6 7]]
7
[1 4 7]


## **Pandas**

In [1]:
import pandas as pd

In [4]:
weather_data={
     'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
} #dict
df=pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
df.shape

(6, 4)

In [7]:
df[1:3]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [8]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [14]:
# df['day'] or
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [15]:
type(df['day'])

pandas.core.series.Series

In [17]:
df[['day','temperature']]

day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [23]:
df['temperature'].max()

35

In [24]:
df[df['temperature']>32]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [25]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
df['day'][df['temperature']==df['temperature'].max()] #day which has max temp or
#df[df['temperature']==df['temperature'].max()]

**Setting index**

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

In [26]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [38]:
#setting day as index
# df.set_index('day')
# df.set_index('day',inplace=True) # inplace =True will save and modify or set index as day
# df

In [31]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [39]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [40]:
df.reset_index(inplace=True)
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [41]:
df.set_index('event',inplace=True)
df

day  temperature  windspeed
event                                  
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

**Linear Regression**

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error
X=np.array([[1],[2],[3],[4]])
y=np.array([1,2,3,4])
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(X_train,y_train)
p=model.predict(X_test)
a=mean_squared_error(y_test,p)
print(a)

0.0


**Decision Trees**

In [43]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
X ,y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
p=model.predict(X_test)
print(p)
s=accuracy_score(y_test,p)
print(s)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
1.0


**Random Forest**

In [44]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
X ,y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)
p=model.predict(X_test)
print(p)
s=accuracy_score(y_test,p)
print(s)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
1.0
